---
# Title: PI-Hole server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: playbook-pull.yml
#
# Description:
#   Playbook for installing a PI-Hole server.
#
# Sources:
#   - https://docs.pi-hole.net/main/prerequisites/
#   - https://github.com/pi-hole/docker-pi-hole
#   - https://discourse.pi-hole.net/t/docker-unable-to-bind-to-port-53/45082/7
#

- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: "Include defaults file ~/.ansible-config.yml"
      include_vars: ~/.ansible-config.yml
      
  vars:
    # -- PI-Hole --
    pihole_region : 'Europe/Amsterdam'
  
  handlers:
  
  roles:
  
  tasks:
    - name: "Include tasks/01-prerequisites.yml"
      include_tasks: tasks/01-prerequisites.yml
 
    - name: "Include tasks/02-docker-pi-hole.yml"
      include_tasks: tasks/02-docker-pi-hole.yml
     
