---
# Title: PI-Hole server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: playbook-pull.yml
#
# Description:
#   Playbook for installing a PI-Hole server.
#
# Sources:
#   - https://docs.pi-hole.net/main/prerequisites/
#   - https://github.com/pi-hole/docker-pi-hole
#

- hosts: localhost
  connection: local
  become: yes
  
  vars:
    # -- PI-Hole --
    pihole_region: 'Europe/Amsterdam'
  
  handlers:
  
  pretasks:
  
  roles:
  
  tasks:
    - name: "Include tasks/01-prerequisites.yml"
      include_tasks: tasks/01-prerequisites.yml
 
    - name: "Include tasks/02-docker-pi-hole.yml"
      include_tasks: tasks/002-docker-pi-hole.yml
     
