---
# Title: PI-Hole server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/01-prerequisites.yml
#
# Description:
#   Playbook for installing a PI-Hole server.
#
- name: "Transfer templates/ubt/01-netcfg-yml.j2 /etc/netplan/01-netcfg.yaml"
  template:
    src: templates/netplan/01-netcfg-yml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0755
    backup: yes
  notify: netplan_apply
  
- name: "Configure UFW firewall IPv4"
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: '80', proto: 'tcp' }
    - { port: '53', proto: 'tcp' }
    - { port: '53', proto: 'udp' }
#    - { port: '67', proto: 'tcp' }
    - { port: '67', proto: 'udp' }

- name: "Configure UFW firewall IPv6"
  community.general.ufw:
    rule: allow
    port: 546:547
    proto: udp

- name: "Stop and disable systemd-resolved (53/tcp) for Pi-Hole"
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: "Configure E-mail configuration, /etc/resolv.conf"
  ansible.builtin.blockinfile:
    path: /etc/resolv.conf
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK - Local DNS configuration -->"
    insertbefore: "^nameserver 127.0.0.53"
    block: |2
      # Google DNS server
      nameserver 8.8.8.8
