---
# Title: PI-Hole server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/02-docker-pi-hole.yml
#
# Description:
#   Playbook for installing a PI-Hole server.
#
- name: "Install APT packages"
  apt:
    pkg:
    - docker
    - docker-compose
    - docker.io
    - python3-docker
    - pwgen
    
- name: "Create directory for local PI-Hole /opt/pi-hole/"
  file:
    path: /opt/pi-hole/
    state: directory

- name: "Download docker-compose.yml to /opt/pi-hole/docker-compose.yml"
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: /opt/pi-hole/docker-compose.yml

- name: "Create and start services"
  community.docker.docker_compose:
    project_src: /opt/pi-hole/
  register: output

- ansible.builtin.debug:
    var: output

