---
# Title: PI-Hole server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/02-docker-pi-hole.yml
#
# Description:
#   Playbook for installing a PI-Hole server.
#
- name: "Install APT packages"
  apt:
    pkg:
    - docker
    - docker-compose
    - docker.io
    - python3-docker
    - pwgen
    
- name: "Create directory for local PI-Hole /opt/pi-hole/"
  file:
    path: /opt/pi-hole/
    state: directory
  
- name: "Download docker-compose.yml to /opt/pi-hole/docker-compose.yml"
  ansible.builtin.template:
    src: templates/pi-hole/docker-compose.yml.j2
    dest: /opt/pi-hole/docker-compose.yml
  
- name: "Stop and disable systemd-resolved (53/tcp) for Pi-Hole"
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: "Check if /opt/authentik/.env exist(s)"
  stat:
    path: /etc/resolv.conf
  register: result_resolv_conf
  
- name: "Configure local DNS /etc/resolv.conf"
  ansible.builtin.blockinfile:
    path: /etc/resolv.conf
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK - Local DNS configuration -->"
    insertbefore: "^nameserver 127.0.0.53"
    block: |2
      # Google DNS server (Temporay)"
      nameserver 8.8.8.8
  when: result_resolv_conf.stat.exists

- name: "Create and start services"
  community.docker.docker_compose:
    project_src: /opt/pi-hole/
    files:
      - docker-compose.yml
  register: output

- ansible.builtin.debug:
    var: output

- name: "Configure local DNS /etc/resolv.conf"
  ansible.builtin.blockinfile:
    path: /etc/resolv.conf
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK - Local DNS configuration -->"
    insertbefore: "^nameserver 127.0.0.53"
    block: |2
      # Local Pi-Hole DNS server
      nameserver 127.0.0.1
  when: result_resolv_conf.stat.exists
